config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants

resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name ,:address, :category, presence: true
  validates :category , inclusion: { :in => [ "chinese", "italian", "japanese", "french", "belgian" ], :message => "this is not a valid category" }
  end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content ,  :rating ,  presence: true
  validates :rating , inclusion: { :in => [ 1, 2, 3, 4, 5 ]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit

  end

  def show
    @reviews = Review.all
  end

  def update
    @restaurant.update(restaurant_params)
       redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
        redirect_to restaurants_path
  end

  private
  def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end

    def find_restaurant
       @restaurant = Restaurant.find(params[:id])
     end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.all

  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
  end

  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new

  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private

  def review_params
    params.require(:review).permit(:content ,:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head><!-- Add these line for detecting device width --><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><!-- [...] --><title>RailsYelpMvp</title><%= csrf_meta_tags %><%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %><%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %></head>

<body>
  <%= yield %>
</body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<nav class="navbar navbar-light bg-faded " style="background-color: #e3f2fd;">
  <form class="form-inline">

    <% params[:action] == "edit" ? @title = "Change restaurant" : @title = "Register an new Restaurant" %>

    <h1> Change restaurant </h1>

    <%= link_to restaurants_path do %> back to list <% end %>

  </form>
</nav>

<div class = "container ">

<%= simple_form_for @restaurant  do |f| %>
            <p>
                        <%= f.label :name %><br>
                        <%= f.text_field :name %>
            </p>
            <p>
                        <%= f.label :address %><br>
                        <%= f.text_area :address %>
            </p>
            <p>
                        <%= f.label :phone_number %><br>
                        <%= f.text_area :phone_number %>
            </p>
            <p>
<%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"], text: "select a value" %>
            </p>
            <p>
                <% params[:action] == "edit" ? @button = "Change" : @button = "Create" %>
                        <%= f.submit @button ,class: 'btn btn-primary' %>
            </p>
<% end %>

</div>

app/views/restaurants/index.html.erb
<nav class="navbar navbar-light bg-faded " style="background-color: #e3f2fd;">
  <form class="form-inline">
    <h1>Restaurants</h1>

    <%= link_to new_restaurant_path do %> Add a new restaurant <% end %>

  </form>
</nav>


<div class="container ">'
  <ul class="list-group">
    <% @restaurants.each do |restaurant| %>
    <li class="list-group-item" >
      <div class="d-inline  text-black"><%= link_to restaurant.name, restaurant_path(restaurant) %></div>
      <div class="d-inline  text-black"><%= restaurant.address  %></div>
      <div class="d-inline  text-black"><%= link_to "edit", edit_restaurant_path(restaurant) %> | <%= link_to " destroy", restaurant_path(restaurant), method:"delete" %>| <%= link_to " view comments", restaurant_path(restaurant) %></div>
      <% end %>
    </li>
  </ul>
</div>

app/views/restaurants/new.html.erb
<nav class="navbar navbar-light bg-faded " style="background-color: #e3f2fd;">
  <form class="form-inline">
    <h1>Register a new Restaurant</h1>

    <%= link_to restaurants_path do %> back to list <% end %>

  </form>
</nav>

<div class = "container ">

<%= simple_form_for @restaurant  do |f| %>
            <p>
                        <%= f.label :name %><br>
                        <%= f.text_field :name %>
            </p>
            <p>
                        <%= f.label :address %><br>
                        <%= f.text_area :address %>
            </p>
            <p>
                        <%= f.label :phone_number %><br>
                        <%= f.text_area :phone_number %>
            </p>
            <p>
<%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"], text: "select a value" %>
            </p>
            <p>
                        <%= f.submit "create" ,class: 'btn btn-primary' %>
            </p>
<% end %>

</div>

app/views/restaurants/show.html.erb
<nav class="navbar navbar-light bg-faded " style="background-color: #e3f2fd;">
  <form class="form-inline">

    <h1><%= @restaurant.name   %>  </h1>
    <h3><%= "#{@restaurant.address} ,  #{@restaurant.phone_number} , specialties #{@restaurant.category} "%> </h3>

    <%= link_to restaurants_path do %> back to list <% end %>

  </form>
</nav>
<%= @restaurant[:id] %>


<div class="container ">'
  <ul class="list-group">
    <% @reviews.each do |review| %>
    <li class="list-group-item" >
      <div class="d-inline  text-black"><%= review.content  %></div>
      <% end %>
    </li>
  </ul>
</div>

<div class="container ">'
  <ul class="list-group">
    <li class="list-group-item" >
      <div class="d-inline  text-black"><%= link_to "edit", edit_review_path(@restaurant) %> | <%= link_to " destroy", restaurant_path(@restaurant), method:"delete" %>| <%= link_to " add comments", restaurant_path(restaurant) %></div>
    </li>
  </ul>
</div>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>